import type { Metadata } from "next";
import "./globals.css";

// import SideBar from "@/components/SideBar";

// const inter = Inter({ subsets: ["latin"] });

import { Roboto } from "next/font/google";
import StoreProvider from "./StoreProvider";

export const metadata: Metadata = {
  title: "LMS Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <main> {children}</main>
        </StoreProvider>
      </body>
    </html>
  );
}
