import type { Metadata } from "next";
import './globals.css'
// import SideBar from "@/components/SideBar";

// const inter = Inter({ subsets: ["latin"] });

import { Roboto } from "next/font/google";

export const metadata: Metadata = {
  title: "LMS Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, 
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font">
      <div>{children}</div>
      </body>
    </html>
  );
}
